gestionLaGrieta/gastosApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.gastos, name="Gastos"),
    path('registro_gastos/', views.registro_gastos, name="Registro_gastos"),
    
]

gestionLaGrieta/gestionLaGrieta/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestionLaGrietaApp.urls')),
    path ('inventario/', include('inventarioApp.urls')),
    path ('pedidos/', include('pedidosApp.urls')),
    path ('gastos/', include('gastosApp.urls')),
    path ('registro_ventas/', include('registro_ventasApp.urls')),
    path ('autenticacion/', include('autenticacionApp.urls')),
]

gestionLaGrieta/pedidosApp/urls.py
from django.urls import path
from . import views

app_name="pedido_mesa"

urlpatterns = [
    path('', views.pedidos, name="Pedidos"),
    path('crear/', views.crear_pedido, name="crear"),
    path('agregar_pago/', views.agregar_metodo_pago, name="agregar_pago"),
    path('agregar_producto/', views.agregar_producto, name="agregar_producto"),
    path('incrementar_cantidad/<int:producto_id>/', views.incrementar_cantidad, name="incrementar_cantidad"),
    path('restar_cantidad/<int:producto_id>/', views.restar_cantidad, name="restar_cantidad"),
    
]

gestionLaGrieta/pedidosApp/models.py
from django.db import models
from django.contrib.auth.models import User
from inventarioApp.models import producto
# Create your models here.

    #Modelo-Tabla Metodo de pago 
class metodo_pago(models.Model):
    titulo = models.CharField(max_length=20)
    imagen = models.ImageField(upload_to= 'metodo_pago')  #subcarpeta para guardar imagenes
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now_add= True)
    class Meta:
        verbose_name = 'metodo_pago'
        verbose_name_plural = 'metodos_pago'
        
    def __str__(self):
        return self.titulo
    
    #Modelo-Tabla pedido
class pedido(models.Model):
    mesa = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add= True)
    updated = models.DateTimeField(auto_now_add= True)
    vendedor =  models.ForeignKey(User, on_delete=models.CASCADE)    #Relacionado a los pedidos (uno a muchos), si se elimina el vendedor, se eliminan todos los pedidos

    class Meta:
        verbose_name = 'pedido'
        verbose_name_plural = 'pedidos'
    
    def __str__(self):
        return self.mesa
    
class pedido_producto(models.Model):
    pedido = models.ForeignKey(pedido, on_delete=models.CASCADE, related_name="productos")
    producto = models.ForeignKey(producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    precio_unitario = models.PositiveIntegerField()
    
    def subtotal(self):
        return self.cantidad * self.precio_unitario
    
    def __str__(self):
        return f"{self.producto.titulo} x {self.cantidad}"
    
class metodo_pago_pedido(models.Model):
    pedido = models.ForeignKey(pedido, on_delete=models.CASCADE, related_name="metodo_pago")
    metodo_pago = models.ForeignKey(metodo_pago, on_delete=models.CASCADE)
    valor = models.PositiveIntegerField()
    

gestionLaGrieta/pedidosApp/forms.py
from django import forms 
from .models import pedido, metodo_pago_pedido,metodo_pago ,pedido_producto
from inventarioApp.models import producto
from django.contrib.auth.models import User

class pedido_form(forms.ModelForm):
    class Meta:
        model= pedido
        fields = ['mesa', 'vendedor']    
        
    def __init__(self, *args, **kwargs):
        super(pedido_form, self).__init__(*args, **kwargs)
        self.fields['vendedor'].queryset = User.objects.all()
        
        
class metodo_pago_form(forms.ModelForm):
    class Meta:
        model = metodo_pago_pedido
        fields = ['metodo_pago', 'valor']
        
    def __init__(self, *args, **kwargs):
        super(metodo_pago_form, self).__init__(*args, **kwargs)
        self.fields['metodo_pago'].queryset = metodo_pago.objects.all()
        self.pedido = pedido


class producto_form(forms.ModelForm):
    class Meta:
        model = pedido_producto
        fields = ['producto', 'cantidad']
        
    def __init__(self, *args, **kwargs):
        super(producto_form, self).__init__(*args, **kwargs)
        self.fields['producto'].queryset = producto.objects.filter(cantidad__gt=0)
        self.pedido = pedido

gestionLaGrieta/pedidosApp/views.py
from django.shortcuts import render, redirect
from .pedido import Pedido
from inventarioApp.models import producto
from pedidosApp.models import pedido, pedido_producto,metodo_pago_pedido, metodo_pago
from .forms import pedido_form, metodo_pago_form, producto_form
from django.db.models import Sum, F, ExpressionWrapper, IntegerField

def pedidos (request):
    productos_base = producto.objects.all()
    productos = pedido_producto.objects.all()
    metodos_pago = metodo_pago.objects.all()
    metodos_pago_pedido = metodo_pago_pedido.objects.all()
    form = pedido_form()
    formp = metodo_pago_form()
    formpr = producto_form()
    pedidos = pedido.objects.annotate(
            total_pagado=Sum('metodo_pago__valor')
            ).order_by('-updated')
    
    for p in pedidos:
        productos = p.productos.all()
        p.total_productos = sum(prod.cantidad * prod.precio_unitario for prod in productos)
    
        if (p.total_pagado or 0) == p.total_productos:
            p.estado = "Pagado"
        else:
            p.estado = "Pendiente"
    return render(request,"pedido/pedidos.html", 
                  {"productos":productos,
                  "productos_base":productos_base,
                  "pedidos":pedidos,
                  "metodos_pago":metodos_pago, 
                  "metodos_pago_pedido":metodos_pago_pedido, 
                  'form':form,
                  'formp':formp, 
                  'formpr':formpr, 
                  })
    
def crear_pedido(request):
    if request.method == "POST":
        form = pedido_form(request.POST)        #Guarda el formulario de creacion
        if form.is_valid():
            form.save()                         #Guarda los valores en la tabla
            return redirect("../")
        else:
            return render(request, 'mesa_pedido/widget_mesa_pedido.html', {'form':form, 'mostrar_modal':True} )
        
    return redirect("../")

def agregar_metodo_pago(request):
    if request.method == "POST":
        pedido_id = request.POST.get('pedido_id')

        try:
            pedido_obj = pedido.objects.get(id=pedido_id)
        except pedido.DoesNotExist:
            return ("Pedido no encontrado")

        # Inicializa el formulario con POST y el objeto pedido
        form = metodo_pago_form(request.POST)
        
        if form.is_valid():
            metodo_pago_pedido_obj = form.save(commit=False)
            metodo_pago_pedido_obj.pedido = pedido_obj
            metodo_pago_pedido_obj.save()
            return redirect("../")  # Redirige principal pedidos
        else:
            return render(request, 'mesa_pedido/widget_mesa_pedido.html', {
                'form': form,
                'pedido': pedido_obj,
                'mostrar_modal': True
            })

    return redirect("../")



def agregar_producto(request):
    if request.method == "POST":
        formpr = producto_form()
        pedido_id = request.POST.get('pedido_id')
        try:
            pedido_obj = pedido.objects.get(id=pedido_id)
        except pedido.DoesNotExist:
            return ("Producto no encontrado")

        # Inicializa el formulario con POST y el objeto pedido
        form = producto_form(request.POST)
        
        if form.is_valid():
            producto_pedido_obj = form.save(commit=False)
            producto_pedido_obj.pedido = pedido_obj
            # Obtener el producto seleccionado
            producto_id = form.cleaned_data['producto'].id
            producto_obj = producto.objects.get(id=producto_id)
            producto_pedido_obj.precio_unitario = producto_obj.precio_unitario
            producto_obj.cantidad -= producto_pedido_obj.cantidad               # Resta la cantidad del inventario
            producto_obj.save()                                                 # Guarda los cambios en el inventario
            producto_pedido_obj.save()
            
            return redirect("../")                                              # Redirige principal pedidos
        else:
            return redirect("../", {
                'formpr': formpr,
                'pedido': pedido_obj,
                'mostrar_modal': True
            })

    return redirect("../")

def incrementar_cantidad(request, producto_id):
    producto_pedido = pedido_producto.objects.get(id=producto_id)
    producto_obj = producto_pedido.producto
    
    if  producto_obj.cantidad > 0:
        
        producto_pedido.cantidad += 1       #Aumenta en 1 la cantidad del producto en el pedido
        producto_pedido.save()
        producto_obj.cantidad -= 1          #Resta en 1 la cantidad del producto en inventario
        producto_obj.save()
        
    return redirect("../../")

def restar_cantidad(request, producto_id):
    producto_pedido = pedido_producto.objects.get(id=producto_id)
    producto_obj = producto_pedido.producto
    if producto_pedido.cantidad > 1:
        producto_pedido.cantidad -= 1
        producto_pedido.save()
        producto_obj.cantidad += 1          #Aumenta en 1 la cantidad del producto en inventario
        producto_obj.save()
    else:
        producto_obj.cantidad += producto_pedido.cantidad  # Devuelve todo al inventario
        producto_obj.save()
        producto_pedido.delete()  # Si quieres eliminar el producto si la cantidad llega a 0
    return redirect("../../")

gestionLaGrieta/pedidosApp/templates/mesa_pedido/widget_mesa_pedido.html
<!-- Pedidos -->
<div>
  {% if user.is_authenticated %}
  <div class="pedidos">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAgregarPedido">
          ➕ Agregar Pedido
    </button>
  </div>

    <!-- Pedidos en base de datos -->
      {% for pedido in pedidos %}
        <div class="pedido" id={{pedido.id}}>
          <div class="pedido-header">
            <td>🪑{{pedido.mesa}}</td>
            <td>📆 Fecha: {{pedido.updated}} </td>
            <button class="btn-toggle" onclick="togglePedido(this)">−</button>
        </div>
        <div class="pedido-content">
          <table>
            <thead>
              <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio</th>
                <th>Subtotal</th>
              </tr>
            </thead>
            <tbody class="pedido-body">
              {% for producto in pedido.productos.all %}
                {% if pedido.id == producto.pedido_id %}
                  <tr>
                    <td>{{producto.producto}}</td>
                    <td>
                      <a class="btn btn-outline-success" href="{% url 'pedido_mesa:restar_cantidad' producto.id %}">-</a>
                      {{producto.cantidad}}
                      <a class="btn btn-outline-success" href="{% url 'pedido_mesa:incrementar_cantidad' producto.id %}">+</a>
                      {% for producto_base in productos_base %}
                        {% if producto_base.cantidad == 0 and producto_base.id == producto.producto_id %}
                          <div class="alert alert-danger" >
                            <p>Quedan 0 unidades en  stock</p>
                          </div>
                        {% endif %}
                        {% if producto_base.cantidad < 0 and producto_base.id == producto.producto_id %}
                          <div class="alert alert-danger" >
                            <p>Cantidad requerida no disponible en stock</p>
                          </div>
                        {% endif %}
                      {% endfor %}
                    </td>
                    <td>{{producto.precio_unitario}}</td>
                    <td>{{producto.subtotal}}</td>
                  </tr>
                {% endif %}
              {% endfor %} 
            </tbody>
          </table>
          <table>
            <tr> <br> </tr>
            <td><button class="btn btn-outline-success btn-agregar-producto" data-bs-toggle="modal" data-bs-target="#modalAgregarProducto">➕ Agregar Producto</button></td>
            <td><button class="btn btn-outline-success btn-agregar-pago" data-bs-toggle="modal" data-bs-target="#modalAgregarMetodoPago">➕ Metodo Pago </button></td>
              <td> <p>{{pedido.estado}}</p> </td>
          <td><div class="total">💰 Total: $ {{ pedido.total_productos }} </div>
          <div class="cancelado" >🧾 Cancelado:${{pedido.total_pagado | default:0}} </div> 
          <div class="metodo-pago">💲: 
            {% for metodo_pago_pedido in metodos_pago_pedido %}
              {% for metodo_pago in metodos_pago %}
                {% if pedido.id == metodo_pago_pedido.pedido_id and metodo_pago.id == metodo_pago_pedido.metodo_pago_id %}
                  <!--{{metodo_pago.titulo}} -->
                  <img  src="{{metodo_pago.imagen.url}}" style="width:5%">
                  $:{{metodo_pago_pedido.valor}}
                {% endif %}
              {% endfor %}
            {% endfor %}
          </div></td>
          </table>
        </div>  
      </div>
      {% endfor %}
    
    {% include "complementos/crear_pedido.html" %}
    {% include "complementos/modal_agregar_producto.html" %}
    {% include "complementos/modal_agregar_metodo_pago.html" %}
  {% else %}
      <tr>
        <td colspan ="4">
          <div class= "alert alert-danger text-center">Sin productos, Inicia Sesion.</div>
        </td>
      </tr>
  {% endif %}

  </div>
</div>




<script> //JavaScrip para minimizar/maximizar cada pedido
    function togglePedido(btn) {
      const content = btn.closest('.pedido').querySelector('.pedido-content');
      if (content.style.display === 'none') {
        content.style.display = 'block';
        btn.textContent = '−';
      } else {
        content.style.display = 'none';
        btn.textContent = '+';
      }
    }
    // Minimiza todos los .pedido-content si el estado es Pagado al cargar la página
    document.addEventListener('DOMContentLoaded', function() {
      document.querySelectorAll('.pedido').forEach(function(pedidoDiv) {
        // Busca el texto del estado dentro del pedido
        var estado = pedidoDiv.querySelector('p')?.textContent?.trim();
        var content = pedidoDiv.querySelector('.pedido-content');
        var btn = pedidoDiv.querySelector('.btn-toggle');
        if (estado === "Pagado") {
          content.style.display = 'none';
          btn.textContent = '+';
        } else {
          content.style.display = 'block';
          btn.textContent = '−';
        }
      });
    });
      
        
     //JavaScrip para enviar el id del pedido para el modal
    document.querySelectorAll('.btn-agregar-pago').forEach(function(boton) {
      boton.addEventListener('click', function() {
        // Encuentra el div más cercano con clase 'pedido'
        const divPedido = this.closest('.pedido');   
        if (divPedido) {
          const pedidoId = divPedido.id; 
          console.log("ID del pedido:", pedidoId);
          const inputHidden = document.getElementById("input-pedido-id");
        if (inputHidden) {
          inputHidden.value = pedidoId;
        } else {
          console.warn("No se encontró el input con ID 'input-pedido-id'");
        }

        }
      });
    });
    document.querySelectorAll('.btn-agregar-producto').forEach(function(boton) {
      boton.addEventListener('click', function() {
        // Encuentra el div más cercano con clase 'pedido'
        const divPedido = this.closest('.pedido');   
        if (divPedido) {
          const pedidoId = divPedido.id; 
          console.log("ID del pedido:", pedidoId);
          const inputHidden = document.getElementById("input-pedido-producto-id");
        if (inputHidden) {
          inputHidden.value = pedidoId;
          console.log("Asignado al input:", inputHidden.value);
        } else {
          console.warn("No se encontró el input con ID 'input-pedido-id'");
        }

        }
      });
    });
</script>

 